"""Divide a coluna usuario_setor em duas colunas. usuario_local e usuario_setor para tb_usuarios

Revision ID: 7b40021aabae
Revises: 9173fef88d30
Create Date: 2024-12-10 09:50:03.110809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b40021aabae'
down_revision: Union[str, None] = '9173fef88d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_demandas')
    op.add_column('tb_usuarios', sa.Column('usuario_local', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_usuarios', 'usuario_local')
    op.create_table('tb_demandas',
    sa.Column('dem_protocolo', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dem_solicitante_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_direcionamento_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_dt_entrada', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_dt_atendimento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_tipo_demanda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_local', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('dem_sala', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('dem_descricao', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('dem_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_prioridade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_dt_final', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_atendido_por_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_tempo_finalizacao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_observacoes', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('dem_link_oficio', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('dem_protocolo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
