"""Coluna 'usuario_vinculo' para a tabela 'tb_usuarios' modificada!

Revision ID: 9173fef88d30
Revises: 08142ec3c812
Create Date: 2024-12-09 10:56:09.499213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9173fef88d30'
down_revision: Union[str, None] = '08142ec3c812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_usuarios', 'usuario_vinculo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_usuarios', 'usuario_vinculo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
