"""Estado inicial da tabela

Revision ID: c95ba554f212
Revises: 
Create Date: 2024-12-09 10:26:44.203670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c95ba554f212'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nva_nome', table_name='tb_niveis_acesso')
    op.drop_table('tb_niveis_acesso')
    op.drop_table('tb_demandas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_demandas',
    sa.Column('dem_protocolo', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dem_solicitante_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_direcionamento_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_dt_entrada', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_dt_atendimento', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_tipo_demanda', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_local', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('dem_sala', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('dem_descricao', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('dem_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_prioridade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_dt_final', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dem_atendido_por_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_tempo_finalizacao', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dem_observacoes', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('dem_link_oficio', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('dem_protocolo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_niveis_acesso',
    sa.Column('nva_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nva_nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nva_desc', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nva_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nva_nome', 'tb_niveis_acesso', ['nva_nome'], unique=True)
    # ### end Alembic commands ###
